excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
  - Solution/Delegate/AppDelegate.swift
  - Solution/Delegate/SceneDelegate.swift
  - Solution/SolutionTests/SolutionTests.swift
  - Solution/SolutionUITests/SolutionUITests.swift
  - Solution/SolutionUITests/SolutionUITestsLaunchTests.swift

disabled_rules: # Default Rules에서 비활성화할 규칙
    
    # 라인 뒤에 공백이 없어야 합니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
    - trailing_whitespace
    
    # 강제 캐스팅은 피해야합니다. https://realm.github.io/SwiftLint/force_cast.html
    - force_cast
    
    # 강제 언래핑은 피해야합니다. https://realm.github.io/SwiftLint/force_unwrapping.html
    - force_unwrapping
    
# Customized Configurable Rules
line_length: 190

